#!/usr/bin/python3

# [SFT]make by [SFT]technologies
#
# Released under the GPLv3 or later
#
# As always, this programm comes with NO WARRANTY...
#
# (c) 2013 Michael Ensslin	<michael@ensslin.cc>
# (c) 2013 Jonas Jelten
# (c) 2013 Andre Kupka
# (c) 2013-2213 Max Veit
#
# Note that [SFT]make is not being developed as a single source file,
# but as a collection of multiple files, one of which is even auto-generated.
# Every source file is capable of running by itself, but contains only a
# fraction of the functionality, and, if run by itself, may need to import
# functionality from the other source files.
#
# Before distribution, all source file fragments are assembled to one
# main file, sftmake, via 'make assembly'.
# This allows for easy usage, but not for easy development.
#
# [SFT]make uses the Wisent Parser Generator to parse assignment statements.
# The grammar is specified in assignmentgrammar.wi in an EBNF-like style.
# Wisent can be invoked via 'make grammar'.
# Wisent is only needed to generate the Parser class, not for running [SFT]make.
#
# The code generated by Wisent, i.e. the classes Unique and Parser, with the
# exception of parts taken verbatim from the input grammar file, are subject
# to the following copyright notice, which is repeated at the beginning of the
# source code block generated by Wisent.
#
# <begin wisent copyright notice>
#
# Copyright (C) 2008, 2009  Jochen Voss <voss@seehuhn.de>
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#   1. Redistributions of source code must retain the above copyright
#      notice, this list of conditions and the following disclaimer.
#
#   2. Redistributions in binary form must reproduce the above
#      copyright notice, this list of conditions and the following
#      disclaimer in the documentation and/or other materials provided
#      with the distribution.
#
#   3. The name of the author may not be used to endorse or promote
#      products derived from this software without specific prior
#      written permission.
#
# This software is provided by the author "as is" and any express or
# implied warranties, including, but not limited to, the implied
# warranties of merchantability and fitness for a particular purpose
# are disclaimed.  In no event shall the author be liable for any
# direct, indirect, incidental, special, exemplary, or consequential
# damages (including, but not limited to, procurement of substitute
# goods or services; loss of use, data, or profits; or business
# interruption) however caused and on any theory of liability, whether
# in contract, strict liability, or tort (including negligence or
# otherwise) arising in any way out of the use of this software, even
# if advised of the possibility of such damage.
#
# <end wisent copyright notice>

# This variable is set in the header.
# It can be checked if the variable is set from each fragment file to
# determine at run-time if its code is run as part of an assembled
# main file, or as a standalone file.
# The check can, e.g. be done via the statement
#	"assembled" in globals()
assembled = True

# End of Header
