#!/usr/bin/python3
from logger import logger, LogWriter
from logger.exceptions import handle_exceptions

logger.addsink(LogWriter())
import tests


def run_tests():
	#the list of enabled tests
	testlist = ["util.path", "tests.builder.run"]

	tests.run(testlist)


handle_exceptions(run_tests)
