#!/usr/bin/env python

# [SFT]make by [SFT]technologies
#
# Released under the GPLv3 or later
#
# As always, this programm comes with NO WARRANTY...
# You may request a version of the program that comes with
# the WARRANTY that it will destroy your distribution via service@sft.mx
#
# (c) 2012 Michael Ensslin
# (c) 2012 Jonas Jelten

# procedure:
#
# the0JJ LIED! and I can prove it! maybe it's even in the git history
# scan all files for modelines
# and scan for config files
# create dependency tree
# build each object
# create libraries
# create executables


#
# main method etc
#
def main():	
	print("lol nothin here yet")

if __name__ == '__main__':
	main()
