#!/usr/bin/env python

from symlink_3parser import parse_assignment

testlines = [
	"var1[abc]+=,var2[cde],var3-=value0 value1 'value2'test",
	"var[\"test\"]=val",
	"var[\'test\']=val",
	"var[test\']\'test]=val",
	"var[test\'bla]=val",
	"var[~]=",
	"var[===]=",
	"var[==!]=",
	"var[==<]=",
	"var[=<]=",
	"var[== ==]=",
	"var[= !(=]=",
	"cflags[c == gcc & !(mode ~= 'a b' | mode == rls))]=test",
	"gschichten [ c == 'clang++' & !(!(!( gschicht =		'iee' && asdf	!= \"d f\" ))) ] = value",
	"gschicht[c==''&&lflags=test]=value",
	"var[(c==value]=val",
	"var[version<=20 && (mode <> rls ; ! c == \"ms proprietary compiler\")]=test",
	"var[a=b | c=d & e=f]=value"
	]

for line in testlines:
	print("Testing parser for line: " + line)
	try:
		print(parse_assignment(line))
	except Exception as e:
		print("Caught exception: " + str(e))
	finally:
		print("")

print("Tests done")
